version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - contact_data:/data
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    volumes:
      - frontend_content:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  contact_data:
  frontend_content:  # Docker-managed volume, no driver_opts needed
