version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - contact_data:/data
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    volumes:
      - frontend_content:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  contact_data:
  frontend_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/frontend/public
