version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - contact_data:/data
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://127.0.0.1:3000/healthz"]
      interval: 20s
      timeout: 3s
      retries: 10
      start_period: 20s

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - frontend_content:/usr/share/nginx/html
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1/ >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  contact_data:
  frontend_content:
