apiVersion: v1
kind: PersistentVolume
metadata:
  name: contact-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/contact-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contact-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
